local DrRayLibrary = loadstring(game:HttpGet("https://raw.githubusercontent.com/hviet2510/NamerPro/main/DrRay-ui.lua"))()
local Tabs = loadstring(game:HttpGet("https://raw.githubusercontent.com/hviet2510/NamerPro/main/modules/tabs.lua"))()
local Buttons = loadstring(game:HttpGet("https://raw.githubusercontent.com/hviet2510/NamerPro/main/modules/buttons.lua"))()
local AutoFarm = loadstring(game:HttpGet("https://raw.githubusercontent.com/hviet2510/NamerPro/main/modules/autofarm.lua"))()
local EnemyList = loadstring(game:HttpGet("https://raw.githubusercontent.com/hviet2510/NamerPro/main/modules/enemylist.lua"))()

local window = DrRayLibrary:Load("NamerPro UI", "Default")

local farmTab = Tabs.Create(window, "Farm Level", "ImageIdFarm")
Buttons.Create(farmTab, "Start Farm", function()
    AutoFarm.Start(EnemyList)
end)
local farmTab = TabsModule.Create(DrRayLibrary, "Farm Level", "ImageIdFarm")
ButtonsModule.Create(farmTab, "Start Farm", function()
    print("[NamerPro] Bắt đầu auto farm")
end)
ButtonsModule.CreateToggle(farmTab, "Auto Farm Toggle", false, function(state)
    print("[NamerPro] Auto Farm: " .. (state and "BẬT" or "TẮT"))
end)

local configTab = TabsModule.Create(DrRayLibrary, "Config", "ImageIdConfig")
ButtonsModule.CreateDropdown(configTab, "Farm Mode", {"Bình Thường", "Nhanh", "An Toàn"}, function(selected)
    print("[NamerPro] Đã chọn mode: " .. selected)
end)

local statsTab = TabsModule.Create(DrRayLibrary, "Stats", "ImageIdStats")
ButtonsModule.CreateToggle(statsTab, "Auto Melee", false, function(state)
    print("[NamerPro] Auto Melee: " .. (state and "BẬT" or "TẮT"))
end)
